version: "3"
services:
    mysql:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./integration-tests/mysql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        depends_on:
            - mysql
        ports:
            - 8888:8080

    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin
        restart: always
        ports:
            - 9411:9411
